routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>['auth']],function(){
    Route::resource('users','UserController');
    Route::resource('roles','RoleController');
});

// Route::group(['middleware'=>['auth']],function(){
//     Route::resource('clientes','ClientesController');
//     Route::resource('roles','RoleController');
// });

Route::group(['prefix'=>'clientes'],function(){
    Route::get('/show','ClientesController@show')->middleware('auth')->name('clientes');
    Route::get('/create','ClientesController@create')->middleware('auth')->name('clientes');
    Route::get('/edit','ClientesController@edit')->middleware('auth')->name('clientes');
    Route::get('/index','ClientesController@index')->middleware('auth')->name('clientes');
});

Route::group(['prefix'=>'produtos'], function(){
    Route::get('/listar', 'ProdutosController@listar')->middleware('auth')->name('produtos');
});


Route::get('/avisos', function () {
    return view('avisos',['nome'=>'Rodrigo','mostrar' => true,
                'avisos' =>[['id'=> 1,'texto' => 'Aviso 1'], 
                            ['id' => 2,'texto'=>'Aviso 2']]     
    ]);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Clientes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Clientes extends Model
{
    protected $fillable = [
        'id',
        'nome', 
        'endereco', 
        'email', 
        'telefone'
    ];
    protected $table = 'Clientes';
        
    public function vendas(){
        return $this->hasMany(Vendas::class,'cliente_id');
    }
}

app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use App\Clientes;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ClientesController extends Controller
{

    private $qdtePag = 5;

    public function __construct() {
         $this->middleware('auth');
    }
    
    public function show($id){
        $cliente = Clientes::find($id);
        return view('clientes.show', compact('cliente'));
    }

    public function index( Request $request){
        $data = Clientes::orderBy('id', 'DESC')->paginate($this->qdtePag);
        return view('clientes.index', compact('data'))->with('i', ($request->input('page', 1)-1)*$this->qdtePag);
    }

    public function create(){
        return view('clientes.create');
    }

    public function store(Request $request){
        $this->validade($request, ['nome' => 'required',
                                   'email' => 'required|email'
                                   ]);
        $input = $request->all();    
        $user = Clientes::create($input);  
        return redirect()->route('clientes.index')-with('success', 'Cliente gravado com sucesso.');                         

    }

    public function edit($id){
        $cliente = Clientes::find($id);
        return view ('clientes.edit', compact('cliente'));
    }
    public function update(Request $request, $id){
        $this->validade($request, ['nome' => 'required',
                                   'email' => 'required|email'
                                   ]);
        $cliente = Clientes::find($id);
        $input = $request->all();
        $cliente->update($input);
        return redirect()->route('clientes.index')->with('success','Cliente atualizado com sucesso!');
    }
    public function destroy($id){
        Clientes::find($id)->delete();
        return redirect()->route('clientes.index')-with('success', 'Cliente removido com sucesso.');
    }
    
}

resources/views/clientes/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Cadastrar Clientes</h2>
        </div>

        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('clientes.index') }}"> Voltar</a>
        </div>
    </div>
</div>
</br>


@if (count($errors) > 0)

  <div class="alert alert-danger">
    <strong>Ops!</strong> Há algo errado com os dados passados.<br><br>
    <ul>
       @foreach ($errors->all() as $error)

         <li>{{ $error }}</li>

       @endforeach
    </ul>
  </div>

@endif

{!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nome:</strong>

            {!! Form::text('name', null, array('placeholder' => 'Nome','class' => 'form-control')) !!}

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Endereço:</strong>

            {!! Form::text('endereco', array('placeholder' => 'Endereço','class' => 'form-control')) !!}

        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
        </div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Telefone:</strong>

            {!! Form::bigInteger('telefone', array('placeholder' => 'Telefone','class' => 'form-control')) !!}

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Perfil:</strong>

            {!! Form::select('roles[]', $roles, [], array('class' => 'form-control','multiple')) !!}

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</div>

{!! Form::close() !!}

@endsection

resources/views/clientes/edit.blade.php
<h1>bem vindo edit</h1>

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Usuários</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('clientes.create') }}"> + Novo usuário</a>
        </div>
    </div>
</div>

<br>

{{-- @if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif --}}


<table class="table table-bordered">

 <tr>
   <th>ID</th>
   <th>Nome</th>
   <th>Email</th>
   <th>Perfil</th>
   <th width="280px">Ação</th>
 </tr>

 @foreach ($data as $key => $user)

  <tr>
    <td>{{ ++$i }}</td>
    <td>{{ $user->name }}</td>
    <td>{{ $user->email }}</td>
    <td>

      @if(!empty($user->getRoleNames()))

        @foreach($user->getRoleNames() as $v)

           <label class="badge badge-success">{{ $v }}</label>

        @endforeach

      @endif

    </td>

    <td>
       <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Mostrar</a>
       <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Editar</a>

        {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}

            {!! Form::submit('Apagar', ['class' => 'btn btn-danger']) !!}

        {!! Form::close() !!}

    </td>
  </tr>

 @endforeach

</table>

{!! $data->render() !!}

@endsection

resources/views/clientes/show.blade.php
@extends('layouts.app')
@section('content')
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th> Nome </th>
            <th> Endereço </th>
        </tr>
    </thead>
    <tbody>
        @foreach($clientes as $cliente)
        <tr>
            <td> {{ $cliente->nome }} </td>
            <td> {{ $cliente->endereco }} </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection