routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>['auth']],function(){
    Route::resource('users','UserController');
    Route::resource('roles','RoleController');
});

// Route::group(['middleware'=>['auth']],function(){
//     Route::resource('clientes','ClientesController');
//     Route::resource('roles','RoleController');
// });

Route::group(['prefix'=>'clientes'],function(){
    Route::get('/show','ClientesController@show')->middleware('auth')->name('clientes');
    Route::get('/create','ClientesController@create')->middleware('auth')->name('clientes');
    Route::get('/edit','ClientesController@edit')->middleware('auth')->name('clientes');
    Route::get('/index','ClientesController@index')->middleware('auth')->name('clientes');
});

Route::group(['prefix'=>'produtos'], function(){
    Route::get('/listar', 'ProdutosController@listar')->middleware('auth')->name('produtos');
});


Route::get('/avisos', function () {
    return view('avisos',['nome'=>'Rodrigo','mostrar' => true,
                'avisos' =>[['id'=> 1,'texto' => 'Aviso 1'], 
                            ['id' => 2,'texto'=>'Aviso 2']]     
    ]);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @if(session()->has('success'))
                <div class="alert alert-success">{{ session()->get('success') }}</div>
            @endif
            @auth
            <div class="row">
                <div class="col-md-3">
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{{ route('users.index') }}">Usuários</a></li>
                        <li class="list-group-item"><a href="{{ route('roles.index') }}"> Perfil da Conta </a></li>
                        <li class="list-group-item"><a href="{{ route('clientes') }}">Clientes</a></li>
                        <li class="list-group-item"><a href="{{ route('produtos') }}">Produtos</a></li>
                    </ul>
                </div>
                <div class="col-md-9">
                    @yield('content')
                </div>
            </div>
            @else
                @yield('content')
            @endauth
        </main>
    </div>
</body>
</html>

resources/views/layouts/externo.blade.php
<html>
    <head><title>@yield('title')</title></head>]
    <body>
        @section('sidebar')
        Uma bela barra superior (use a imagina&ccedil;&atilde;o) <br>
        ----------------------------------------------
        @show
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>